import type { AppComplaint, Officer, Notification } from "../types";

export const complaints: AppComplaint[] = [
  {
    id: "MCL-BB-0042",
    title: "Waterlogging on main road",
    citizen: "Ravinder Singh",
    phone: "9876543210",
    ward: "Ward 12",
    officer: "Sonia Mehta",
    status: "Pending approval",
    registered: "2026-09-01",
    zone: "Zone-A",
    block: "Block 2",
    address: "Near Model Town Crossing, Ludhiana",
    description:
      "Heavy rain has caused water accumulation near the traffic signal, blocking access for pedestrians and motorists.",
    assignedOfficer: "Sonia Mehta",
    atp: "Amit Sharma",
    daysOpen: 3,
    timeline: [
      { label: "Pending approval", timestamp: "Today, 11:45 AM", actor: "Amit Sharma", accent: "amber" },
      { label: "Resolution submitted", timestamp: "Yesterday, 2:10 PM", actor: "Sonia Mehta", accent: "purple" },
      { label: "In progress", timestamp: "Yesterday, 8:00 AM", actor: "Sonia Mehta", accent: "amber" },
      { label: "Assigned", timestamp: "Sep 1, 4:15 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Sep 1, 3:50 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
  {
    id: "MCL-BB-0041",
    title: "Streetlight outage near school",
    citizen: "Manpreet Kaur",
    phone: "9811122233",
    ward: "Ward 8",
    officer: "Rohit Verma",
    status: "Assigned",
    registered: "2026-08-29",
    zone: "Zone-C",
    block: "Block 1",
    address: "School Road, Pakhowal Road",
    description: "Streetlight is non-functional near the school gate causing visibility issues during evening hours.",
    assignedOfficer: "Rohit Verma",
    atp: "Nitin Malhotra",
    daysOpen: 6,
    timeline: [
      { label: "Assigned", timestamp: "Aug 29, 5:20 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Aug 29, 4:35 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
  {
    id: "MCL-BB-0039",
    title: "Broken drainage cover",
    citizen: "Harjot Singh",
    phone: "9988776655",
    ward: "Ward 5",
    officer: "Priya Khanna",
    status: "Approved / Closed",
    registered: "2026-08-19",
    zone: "Zone-B",
    block: "Block 3",
    address: "Near busy market lane, Ferozepur Road",
    description: "Open drainage cover poses safety risk to pedestrians and two-wheel riders.",
    assignedOfficer: "Priya Khanna",
    atp: "Anil Bansal",
    daysOpen: 12,
    timeline: [
      { label: "Approved / Closed", timestamp: "Aug 20, 10:06 AM", actor: "Anil Bansal", accent: "green" },
      { label: "Pending approval", timestamp: "Aug 20, 9:20 AM", actor: "Anil Bansal", accent: "amber" },
      { label: "Resolution submitted", timestamp: "Aug 20, 8:30 AM", actor: "Priya Khanna", accent: "purple" },
      { label: "Assigned", timestamp: "Aug 19, 5:10 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Aug 19, 4:00 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
  {
    id: "MCL-BB-0038",
    title: "Garbage dumping hotspot",
    citizen: "Rajiv Arora",
    phone: "9001122334",
    ward: "Ward 2",
    officer: "Aarti Nanda",
    status: "Rejected",
    registered: "2026-08-16",
    zone: "Zone-D",
    block: "Block 4",
    address: "Rhythm Road, near bus stand",
    description: "Public dumping at the roadside has created unpleasant conditions and increased insect activity.",
    assignedOfficer: "Aarti Nanda",
    atp: "Amit Sharma",
    daysOpen: 15,
    timeline: [
      { label: "Rejected", timestamp: "Aug 17, 3:40 PM", actor: "Amit Sharma", accent: "red" },
      { label: "Resolution submitted", timestamp: "Aug 17, 1:30 PM", actor: "Aarti Nanda", accent: "purple" },
      { label: "Assigned", timestamp: "Aug 16, 5:15 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Aug 16, 4:20 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
  {
    id: "MCL-BB-0033",
    title: "Broken footpath tiles",
    citizen: "Vinod Kumar",
    phone: "9823456789",
    ward: "Ward 9",
    officer: "Karan Gill",
    status: "In progress",
    registered: "2026-08-10",
    zone: "Zone-A",
    block: "Block 2",
    address: "Opposite BRS Nagar gate",
    description: "Concrete tiles on the footpath are broken and unsafe for pedestrians.",
    assignedOfficer: "Karan Gill",
    atp: "Neha Sood",
    daysOpen: 18,
    timeline: [
      { label: "In progress", timestamp: "Aug 11, 9:10 AM", actor: "Karan Gill", accent: "amber" },
      { label: "Assigned", timestamp: "Aug 10, 4:45 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Aug 10, 4:20 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
  {
    id: "MCL-BB-0031",
    title: "Overflowing sewer manhole",
    citizen: "Satnam Singh",
    phone: "9712345678",
    ward: "Ward 14",
    officer: "Ishita Jain",
    status: "Resolution submitted",
    registered: "2026-08-07",
    zone: "Zone-C",
    block: "Block 5",
    address: "Near railway station market",
    description: "The sewer chamber overflow is creating a hygiene problem and odour nuisance in the market lane.",
    assignedOfficer: "Ishita Jain",
    atp: "Nitin Malhotra",
    daysOpen: 23,
    timeline: [
      { label: "Resolution submitted", timestamp: "Aug 9, 11:28 AM", actor: "Ishita Jain", accent: "purple" },
      { label: "Assigned", timestamp: "Aug 7, 3:20 PM", actor: "Ludhiana Operations", accent: "blue" },
      { label: "Registered", timestamp: "Aug 7, 2:40 PM", actor: "Operator Desk", accent: "neutral" },
    ],
  },
];

export const officers: Officer[] = [
  { name: "Amit Kumar", designation: "Officer", zone: "Zone 1", blocks: ["Block A"], wards: 2, activeComplaints: 3 },
  { name: "Rajesh Singh", designation: "Officer", zone: "Zone 1", blocks: ["Block B"], wards: 2, activeComplaints: 2 },
  { name: "Rohit Sharma", designation: "Officer", zone: "Zone 2", blocks: ["Block C"], wards: 2, activeComplaints: 4 },
  { name: "Kirpal Singh", designation: "Officer", zone: "Zone 2", blocks: ["Block D"], wards: 2, activeComplaints: 3 },
  { name: "Sunil Kumar", designation: "Officer", zone: "Zone 3", blocks: ["Block E"], wards: 2, activeComplaints: 2 },
  { name: "Vikram Singh", designation: "Officer", zone: "Zone 3", blocks: ["Block F"], wards: 2, activeComplaints: 3 },
  { name: "Mandeep Walia", designation: "Officer", zone: "Zone 1", blocks: ["Block A"], wards: 2, activeComplaints: 2 },
  { name: "Jatinder Pal", designation: "Officer", zone: "Zone 1", blocks: ["Block B"], wards: 2, activeComplaints: 1 },
  { name: "Sandeep Kumar", designation: "Officer", zone: "Zone 2", blocks: ["Block C"], wards: 2, activeComplaints: 2 },
  { name: "Rakesh Mehta", designation: "Officer", zone: "Zone 2", blocks: ["Block D"], wards: 2, activeComplaints: 2 },
  { name: "Harpreet Singh", designation: "Officer", zone: "Zone 3", blocks: ["Block E"], wards: 2, activeComplaints: 1 },
  { name: "Navdeep Singh", designation: "Officer", zone: "Zone 3", blocks: ["Block F"], wards: 2, activeComplaints: 2 },
];

export const notifications: Notification[] = [
  { title: "Resolution submitted — MCL-BB-0042", body: "Sonia Mehta • Ward 12", time: "2 hours ago", unread: true, tone: "amber" },
  { title: "Complaint assigned — MCL-BB-0041", body: "Rohit Verma • Ward 8", time: "4 hours ago", unread: true, tone: "blue" },
  { title: "Approval required — MCL-BB-0039", body: "Priya Khanna • Ward 5", time: "1 day ago", unread: false, tone: "green" },
  { title: "Complaint rejected — MCL-BB-0038", body: "Aarti Nanda • Ward 2", time: "2 days ago", unread: false, tone: "red" },
  { title: "Status updated — MCL-BB-0033", body: "Karan Gill • Ward 9", time: "3 days ago", unread: false, tone: "purple" },
];
